### ISSUE TITLE
Linking to specific tabs

### ISSUE THREAD

**Issue by Serdaro** [asciidoctor/asciidoctor-tabs#24]
It'd be very nice if we could be able to link to a specific tab within a tabbed code block.

Currently, when we give an ID to a tab and xref it, the link goes to the first tab of the block, not to the ID'ed one.

**Comment by mojavelinux** [comment]
To get this working, we need to do some management of the URL hash. Here's the behavior I've decided on (for now).

* On page load, activate the tab that matches the URL fragment, if any. Leave the URL as is.
* When the hash is changed by clicking on an internal link, respond to the hashchange event to activate the tab that matches the URL fragment, if any. Leave the URL as is.
* When a tab is clicked, discretely clear the URL fragment on the hash using replaceState. This ensures that subsequent internal links will trigger the hashchange event.
