### ISSUE TITLE
Feature request: installation instructions for NixOS

### ISSUE THREAD

**Issue by refaelsh** [asciidoctor/asciidoctor-tabs#36]
Hi all,

Please add installation instruction for NixOS.

Thanks.

**Comment by mojavelinux** [comment]
Instructions have been provided for how to install the gem using Ruby packaging (Bundler and gem). As of now, those are the only ways to install this library, and they are universal. Therefore, we will not be adding any additional instructions at this time.

If you know of another way to install the gem and would like to share it, you are free to submit a pull request or share that information in the project chat at https://chat.asciidoctor.org.

**Comment by refaelsh** [comment]
I understand. Thank you :-)
