### ISSUE TITLE
Implement role attribute

### ISSUE THREAD

**Issue by cunka** [asciidoctor/asciidoctor-tabs#43]
Would like to see **asciidoctor-tabs** have a full **role** attribute implemented and working. 
This would keep it additionally consistent with the way other blocks works.

- _e.g. [tabs.chocolate]_

[https://docs.asciidoctor.org/asciidoc/latest/attributes/role/](url)

Currently only the ID is working. 

- _e.g. [tabs#redWine]_

Currently, If we lazily put a "." proceeding the name, _(example: [tabs.])_ then the terminal will report an _empty role_. 

The idea behind using the _role_ feature on a block is the ability to use a CSS style on 1 or more tabset(s).
Some branding styling guidelines mandate the use of a class ahead of an ID, simply for streamlining into an existing website. Having the use of a _role_ makes the implementation easier.

**Comment by mojavelinux** [comment]
This seems like a reasonable request.

> If we lazily put a "." proceeding the name, (example: [tabs.]) then the terminal will report an empty role.

That's normal behavior of Asciidoctor and is expected.
