### ISSUE TITLE
Nested tabsets

### ISSUE THREAD

**Issue by eric-schneider** [asciidoctor/asciidoctor-tabs#55]
I’m trying to determine if asciidoctor-tabs supports nested tabsets (placing a tabset within another tabset). If it doesn't, then everything I describe below is probably moot and this issue can probably be closed or transitioned to an enhancement request.

The issue I’m seeing is that, on initial page load, nested tabsets appear to render correctly, but upon switching between the top-level tabs, any nested tabsets underneath show up as floating tabs without any content or border. Curiously, though, if I click on one of the floating tabs, its content will (re)appear correctly. 

I’m trying to troubleshoot whether the problem lies with:

- my AsciiDoc syntax,
- my implementation of asciidoctor-tabs,
- the Antora Default UI,
- an issue with the asciidoctor-tabs extension itself, or
- an issue with Antora/Asciidoctor more generally

**Visual aid showing the issue in action:**

![asciidoctor-tabs-issue](https://github.com/asciidoctor/asciidoctor-tabs/assets/37347760/e0ce1250-61cb-4a2e-8fb7-2c8fc512517f)

**My environment:**

- Operating System: macOS 13.3.1
- Browser: Firefox, Chrome
- node: 18.16.0
- @asciidoctor/tabs: 1.0.0-beta.3
- antora: 3.1.3
- UI: Antora Default UI (https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable)
    - with Supplemental UI defined according to the [Use with Antora](https://github.com/asciidoctor/asciidoctor-tabs/blob/main/docs/use-with-antora.adoc) guide.

**My AsciiDoc (mildly sanitized for sake of demonstration):**

Page:

```asciidoc
[tabs]
======
Debian/Ubuntu (APT)::
+
include::guides:partial$cassandra-install-apt.adoc[]

CentOS/RHEL (YUM)::
+
include::guides:partial$cassandra-install-yum.adoc[]

Tarball::
+
include::guides:partial$cassandra-install-tarball.adoc[]
======
```

Partial 1 (_cassandra-install-apt.adoc_):

```asciidoc
. Step 1
+
[tabs]
====
Command::
+
--
[source,shell,subs="attributes+"]
----
include::example$bash/commands/get-deb-package.sh[]
----
--

Result::
+
--
[source,console,subs="attributes+"]
----
include::example$bash/results/get-deb-package.result[]
----
--
====

. Step 2
+
[tabs]
====
cURL::
+
--
[source,shell]
----
include::guides:example$bash/commands/curl-add-repo-keys.sh[]
----
--

Wget::
+
--
[source,shell]
----
include::guides:example$bash/commands/wget-add-repo-keys.sh[]
----
--

Result::
+
--
[source,console]
----
include::guides:example$bash/results/add-repo-keys.result[]
----
--
====

. Step 3
+
[source,shell]
----
include::guides:example$bash/commands/apt-get-update.sh[]
----

. Step 4
+
[source,shell]
----
include::guides:example$bash/commands/apt-add-key.sh[]
----

. Step 5
+
[source,shell,subs="attributes+"]
----
include::guides:example$bash/commands/apt-get-cass.sh[]
----

```

I can post the content of the additional partials if necessary for further troubleshooting.

**Comment by mojavelinux** [comment]
Technically, yes, nested tabs are supported. However, the script that manages the behavior is over-matching tab lists and tab panels. This is a side-effect of imprecise CSS selector matching. If the code more carefully selected only the elements for the tabset the user is interacting with, then the nested tabs would work as expected.

> any nested tabsets underneath show up as floating tabs without any content or border. 

This only means that no tab (and its corresponding panel) is selected.

Here's the sketch of the logic the script needs to use:

```js
forEach.call(tabs.querySelector('.tablist').querySelectorAll('.tab'), function (el) {
  toggleSelected(el, el === tab)
})
var nextPanel = tabs.querySelector('.tabpanel')
while (nextPanel) {
  toggleHidden(nextPanel, nextPanel !== panel)
  if (!(nextPanel = nextPanel.nextElementSibling).classList.contains('tabpanel')) nextPanel = null
}
```

**Comment by mojavelinux** [comment]
I also found that if a table is contained without a tab in nested tabs, it was getting wrapped in a tablecontainer div twice. The root of the problem is the same. The selector that is used to process tables was going too deep.
