### ISSUE TITLE
Allow overriding attributes inside tabs

### ISSUE THREAD

**Issue by ekohl** [asciidoctor/asciidoctor-tabs#72]
I'd like to define attributes inside a tab so I can easily include the same file with different contents.

The exact use case is to provide installation instructions for Debian 11, Ubuntu 20.04 and Ubuntu 22.04. They're all the very similar, but obviously the exact versions differ.

I tried it like this:

```asciidoc
:first: before
:override: pre
[tabs]
====
Tab A::
:attr: X
:override: inside1
{first} {override} {attr}
Tab B::
:attr: Y
:override: inside2
{first} {override} {attr}
====
```

But this renders literal: `:attr: X :override: inside1 before pre {attr}`

![Screen Shot 2024-07-01 at 19 31 46](https://github.com/asciidoctor/asciidoctor-tabs/assets/155810/43799eff-d4f3-4e6e-b99f-267cb4092e68)

Am I doing something wrong or is this not supported? Could it be supported?

```console
$ bundle show | grep asciidoc
  * asciidoctor (2.0.23)
  * asciidoctor-tabs (1.0.0.beta.6)
```

**Comment by mojavelinux** [comment]
Please ask for help in the project chat at https://chat.asciidoctor.org. I'll be happy to follow up there. The issue tracker is not a support portal, as stated on https://docs.asciidoctor.org/about/get-help/#chat

**Comment by ekohl** [comment]
Sorry, I only read the README on GitHub. Also didn't see a `CONTRIBUTING.md`. You may way to consider that project wide (in a `.github` project). Then the New Issue form creates a link to it.

**Comment by mojavelinux** [comment]
That's because this is not the primary Asciidoctor project. In fact, it still hasn't been promoted to the docs site as an official project yet. With that said, I'll add the issue template that we use in the main project so that at least there is information about the chat.

**Comment by ekohl** [comment]
I thought you could also create it in `.github`. At least in Vox Pupuli we have our `SECURITY.md` and others centralized: https://github.com/voxpupuli/.github

But I can't find a good source on what is and isn't supported. Searching for "github" and "contributing" isn't exactly targeted ;)

**Comment by mojavelinux** [comment]
Not all projects follow the exact same help policy since they are operated by different maintainers, so I prefer not to use the global template. Adding it per repository for the ones I maintain works better for me and the group.

We do use .github for the code of conduct, which is universal.

**Comment by ekohl** [comment]
Fair enough, we have the same problem with `CONTRIBUTING.md` because some repos are gems, some are Puppet modules.
